development:
  adapter: mysql2
  database: shorturls_development
  username: root
  password: "1234"

test:
  adapter: mysql2
  database: shorturls_test
  username: root
  password: "1234"

production:
  host: ""
  adapter: postgresql
  database: ""
  username: ""
  password: ""
  port: 5432