development:
  adapter: mysql2
  database: shorturls_development
  username: root
  password: "1234"

test:
  adapter: mysql2
  database: shorturls_test
  username: root
  password: "1234"

production:
  host: "ec2-23-23-237-0.compute-1.amazonaws.com"
  adapter: postgresql
  database: "d6pgdph55ktg7p"
  username: "afrfqcjxgjqqbp"
  password: "pNJ_iiWZFPVpxu7YWwFKVZjlXG"
  port: 5432